### ISSUE TITLE
Laggy rendering while looking to ground

### ISSUE THREAD

**Issue by erm3nda** [Duion/Uebergame#218]
Hi.

Game lags rendering when i look at ground, and a bit too when i aim to sky.
I've treid even the Potato settings, but still notice the rendering lag. 

When i don't look at ground it's very smoth, even with higher graphs settings than potato.

I am using VGA compatible controller: Intel Corporation Device 22b1 (rev 21), which is a IntelHD (laptop) integrated graphic.

It made me thing that ground texture is loaded to memory *every* time you look at it, causing a little bottleneck to the render.
I had the problem on both stages, PB and Building, so is likely related on how the ground texture is loaded.

**Comment by Duion** [comment]
Did you try on an empty level without terrain? Open the world editor and open tools/levels/construct.mis it is a blank mission with almost nothing in it, or just delete the terrain, since the empty level will probably boost the fps overall.
Otherwise I don't know the exact model, but it sounds very old and may not be able to run the rendering techniques used in Uebergame.
When I run on slow GPU I keep the resolution to 1024x768 or so, this makes it run super fast then.

**Comment by erm3nda** [comment]
I tried it, hidding grass and ground itself. 
Seems my chipset is just not goog enough.

OpenGL.IntelOpenSourceTechnologyCenter.MesaDRIIntelRHDGraphicsCherryview.33CoreProfileMesa1120.cs exists

GFXCardProfiler (OpenGL) - Unknown capability 'GL::Workaround::noCompressedNPoTTextures'.

When it tries to render near textures the shit comes. It works super smooth on distances, blurried textures

Anyway, thanks.

**Comment by Duion** [comment]
Yes maybe the GPU does not have enough texture bandwidth or what it is called.
Try lowering texture quality, then it should work, it reduces it really low.
Yes, that thing is a bug, but it is already fixed in the engine development branch, it will make it in in the next version.
