### ISSUE TITLE
Nosteam 1.0.7 Linux - Missing player model + no master servers found

### ISSUE THREAD

**Issue by erm3nda** [Duion/Uebergame#219]
Well.

I found that game on Steam, and it worked. Yesterday i downloaded the 1.0.7 directly from the Duion.com webpage and seems that something is missing.

No servers found when pingin master.

Also, the base model in the settings is missing, it only displays the weapon.
In game it's shown.

I've uploaded a image for convenience: http://imgur.com/a/6QHMF

**Comment by Duion** [comment]
Well this should not happen, since it is the same version.
Most issue under Linux are file persmission issues or case sensitive issues. You sure you owned the files properly? Steam propablly does that automatically for you.
Otherwise look in console.log for errors, but I don't think it is a problem with the game itself, since this never happened before.

**Comment by Duion** [comment]
Is this solved? There is also a new version out.

**Comment by erm3nda** [comment]
Didn't tried anymore, that little GPU was not made to play :D sorry.
